language: ruby
services:
  - postgresql
addons:
  postgresql: '9.4'
  code_climate:
    repo_token:
      secure: "IKDGTPnFNfa4JJvuajEZpD3OyH4vlUsO/GvOpikYjr6JwZi1n/V+B8dJGfy0zJ2sQ+ttpIUzXeu1FrM24QnDNL6y+Z9avUZzHoAdVH2DifhUIo/LrdZFFlISKhS/tjOMqZNwYK2Az16VF6NRVHr+N9m0evRLzCHdgj8gqGO9qTVtISd6CgDAcuMdygOtw7OD2+Kc8Ew7PLymnoLGEwmFXpi+N/gkYdTgd2fEIppRRvVKMb5e0qslHn1gaa6JvZzd1JwY3GSd03p416WjyNFk16Z4ipK9Je1n3LPMI6rijQclsv+0R/ia11Slc8yoOdvQiFsyajAMiAD598KcowfJp7SXVuPRCwnl28nssyFgyh6VhgDUdEQxpOuBRyXN/pIl6f4oDkhK88SgYK/IOhfi7l1swF4acViOr1Bw9X9Rk1b4vkXAaI8I5cQ7FV6LGbba27cQEAxAet3WoR819qrdag6SnmK2yIFSj8OtU9E0GBYmEieP63TMDO3iQgd3/56dTd1yhlZL3EI8a+iwZs1CcgHIM13tTsbp2TwQgC5DTVuhg7pJZNegaupdOiMh3NjpF0JngtaiGvzvBvpwmktMKSyNMfnk+l98qIp521p96w9DLJd+WwcHaepscm8AYVjvRt8KLEDnwv0OrO+h9c4Pyaimc91mOWuWEpmd4jk0jB8="
before_script:
  - psql -c 'create database "dockerhub2ci_test";' -U postgres
env:
  - START_SIMPLECOV=1
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
deploy:
  provider: heroku
  api_key:
    secure: SQPSjtmgbsbm8g7k4IBEaCI2xVbl7y8Af+CYsKE1LujHXFjmZi/poKK1H/q9UGkXs1tbg7h2ebAdMe7BXLhf5f0tcEWY2HC+Ve9tX9NgAu71BL/1uoMMB7PuPjl7FFAgy+RDirAqwuUfalhrvHkBy2m4hjBmfm9nkX5DsmlnKK2bOLPUhVYb0gC9+lQFlAR4CVr+AUFw+gHiPmYyIgsv8UdARTrJfjjE0F/RC8aTXnsh7yHeBfiFCGmvTKApoLp82E9L/rJvNaohtkmW2TAuRoENkEs/lWmwrIP9/RIXgb9x/Q+oBjcVv50O3DElK8LOc99P91EcoJlDpdhnskkTyrd61g1ufSpf08xLtcXbEce7aYH2YCE0WWmDb/J5AqSyz+dE1yM+kP10ANyLc2JOdv0gxFZCOUQYkns2+l6r7guZtOARn0dO5TdYU83jOqXjHJC8ot7d7440WuEfGnRw48EOE/Hk8qX6EIBS8oFPOwFgogfDU02KN3wt5cSZGs3zQiKeKNIwPU3MPmVWW2h1JSCCDSq1nszy5hh6IBIDDOxVjL6qbiewp4kEtswSi6ZL9A42EBpHtoG4BTNa85qzT/NbaB6tLomBbL0+zfvHawswVW4LjENsPm3Y4gFPRFeudCzGYc7Yh6DnpkVCpwU5gTUH+s66vDbI0eERdrBX3u0=
  run:
    - rake db:migrate
